### ISSUE TITLE
Add GNS3 versions of the symbols to this repository?

### ISSUE THREAD

**Issue by ehlers** [ecceman/affinity#1]
I've created GNS3 optimized versions of your fine symbol set by using the Inkscape program, see https://github.com/ehlers/affinity/tree/GNS3

Changes:
- size changed to 60x60px
- reduced the number of waypoints by Inkscape path simplify, that reduces the size of the symbols
- blue symbols created from the gray version by text replacement (using `sed`)

Two symbols are missing in the svg directory, for GNS3 I recreated them:
- svg/circle/blue/c_client_vm_blue.svg
- svg/square/gray/sq_switch.svg

I see two options now, both are fine for me.
I can create a pull request, that allows an easy integration of the GNS3 symbols into your repository.
Or I keep the GNS3 symbols in my repository and update them, when you change the originals.

What do you think?

**Comment by ecceman** [comment]
Nice! If you feel like running a GNS3-optimized repos that would be great. I will focus on getting a few more symbols out and new colors. 

The client vm symbol I'm not happy with, it should not be there. I will re-design it but I have no good idea right now what it should look like. The switch symbol is added.

**Comment by ehlers** [comment]
Fine, I will run a repo with GNS3 optimized symbols added.

**Comment by ehlers** [comment]
The symbols are added to GNS3, so my repository is superfluous, I deleted it. The GNS3 symbols can be downloaded from <https://github.com/GNS3/gns3-server/tree/2.2/gns3server/symbols/affinity>.

**Comment by ycharbi** [comment]
@ehlers 
Hello,
Can you please give your `sed` command for change color of _SVG_ ?
I will like help this project with my small skills :)

**Comment by ecceman** [comment]
Gray: HUE: 0,0,30, RGB: 77,77,77
Blue: HSL: 216,61,45, RGB: 45,103.185

sed -e "s/rgb(77,77,77)/rgb(45,103,185)/" c_shield_gray.svg >c_shield_blue.svg
