### ISSUE TITLE
Create new icons with clean code

### ISSUE THREAD

**Issue by ycharbi** [ecceman/affinity#14]
Hello,

I've been following your project with great interest for a while now and I'm wondering how to create icons with such light code as the ones you've created?

I have created some with Inkscape (which have since been added to the project) but the source code is filthy because it's very polished with useless code. Do you master SVG to the point of doing it with a word processor or is there a tool that can do it?

I don't see myself contributing to the project by proposing icons with filthy source code...

**Comment by ecceman** [comment]
I don't do anything special with the code, It just gets that way when I export to SVG. I have found that it depends heavily on how you create the objects. If I mess around with complex shapes and convert objects to curves etc the code gets way bigger. Some of the symbols can probably be optimized, but I don't see a need to focus on that as long as they work as expected.

**Comment by ycharbi** [comment]
Ok thank you for your answer.
