### ISSUE TITLE
symbols as Visio stencil?

### ISSUE THREAD

**Issue by taduo** [ecceman/affinity#16]
Is it possible to create a way to import them easily to Visio?

I found this one, but I was looking for the square ones.
https://github.com/sekiguchi-nagisa/affinity/tree/master/visio

There are other ways to import that stay categorized and labeled?

Thanks

**Comment by ecceman** [comment]
I'm no visio expert, but I tried it earlier and it just broke all the time. Also, I'm not sure about any potential license issues regarding visio, and the 365-version seems VERY limited for now so I decided not to bother with visio at all.
