### ISSUE TITLE
Visio stencils in other colors than blue?

### ISSUE THREAD

**Issue by ldev** [ecceman/affinity#2]
Love your work on this symbol set! So clean and pixel perfect.

Any possibilities you share how you made the visio stencils out of the svg set? My goal is to have the symbols as Visio stencils in black and in gray.

Best regards,
Jonas Lindstad

**Comment by ecceman** [comment]
Yes, more colors will arrive. 
It was a while since I created the visio stencils, I don't recall exactly how I did it, but it was not hard. Visio stencils now removed, I cannot be bothered to maintain it, it's Windows only. :(
