### ISSUE TITLE
implementation issues

### ISSUE THREAD

**Issue by bijoube** [ecceman/affinity#3]
hello, thank you very much to share that peace of art with every body, but still do have issues when i want to implement them on PT because of there dimension, i had to convert them to png and then adjusting the size with paint to fit in PT. but when doing that the image lose its pixels quality, please help me!!

best wishes.
![iRouter](https://user-images.githubusercontent.com/46846701/55591931-37a6b200-5737-11e9-98c4-a2414a169d4b.png)

**Comment by ecceman** [comment]
Sorry for being super-slow to respond. If this is still an issue, create a new issue.
