### ISSUE TITLE
Phone Stencil?

### ISSUE THREAD

**Issue by bryonadams** [ecceman/affinity#8]
Are you still working on these? I want to request a stencil for a phone if possible. I really like these but I work in telephony and don't see one in here.

Thanks!

**Comment by ecceman** [comment]
> Are you still working on these? I want to request a stencil for a phone if possible. I really like these but I work in telephony and don't see one in here.
> 
> Thanks!

Sure I can fix that. I work on these when I miss a symbol of if I get a req.

**Comment by ecceman** [comment]
A bunch of phone symbols added. Hope you like them.

**Comment by bryonadams** [comment]
They're fantastic! Thank you very much.
